### ISSUE TITLE
Add posibility to run ngx-restangular with Angular 5

### ISSUE THREAD

**Issue by kotmatpockuh** [2muchcoffeecom/ngx-restangular#111]
Now I'm getting such errors:

```
WARNING in ./node_modules/ngx-restangular/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (D:\svn\MyProject\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (D:\svn\MyProject\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (D:\svn\MyProject\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (D:\svn\MyProject\node_modules\webpack\lib\Compiler.js:506:17)
    at D:\svn\MyProject\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\svn\MyProject\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (D:\svn\MyProject\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ngx-restangular/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ngx-restangular/dist/esm/src/ngx-restangular.module.js
 @ ./node_modules/ngx-restangular/dist/esm/src/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/ngx-restangular/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (D:\svn\MyProject\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (D:\svn\MyProject\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (D:\svn\MyProject\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (D:\svn\MyProject\node_modules\webpack\lib\Compiler.js:506:17)
    at D:\svn\MyProject\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\svn\MyProject\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (D:\svn\MyProject\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ngx-restangular/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ngx-restangular/dist/esm/src/ngx-restangular.module.js
 @ ./node_modules/ngx-restangular/dist/esm/src/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by gtamas** [comment]
These are warnings, however there are actual errors too:

Angular uses RxJS 5.5.x, which is not compatible with ngx-restangular.
(https://github.com/2muchcoffeecom/ngx-restangular/issues/110)

Besides, if I do this:

```
import {RestangularModule} from "ngx-restangular";
.....

@NgModule({
    imports: [
        RestangularModule
        .....

```
then Angular compiles the code, but the following error appears when I load the page:

Unexpected value 'RestangularModule' imported by the module 'SomeModule'. Please add a @NgModule annotation.

Also, now  HttpClientModule and HttpClient should be used instead of HttpModule and Http, but Restangular might still work with the old ones. 

I'm about to start a new Angular project and I would like to use Angular 5 and Restangular, however, this doesn't seem to be possible at the moment.  Will the library be upgraded to Angular 5 anytime soon or should I look into other alternatives?

**Comment by logvinoleg89** [comment]
Added. Please update to 1.1.0 version!

**Comment by jason-ibisi** [comment]
I still have the same issue even after updating all dependencies

**Comment by iCodr8** [comment]
I am using Restangular in version 2.0.2 and the problem still exists.
