### ISSUE TITLE
Error building on Angular5

### ISSUE THREAD

**Issue by bpalermo** [2muchcoffeecom/ngx-restangular#113]
running

`
ng build --prod --aot --no-sourcemap --environment=prod
`

gives, on Angular5:

`
ERROR in ./node_modules/rxjs/observable/BoundNodeCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (/projeto/node_modules/typescript/lib/typescript.js:9341:17)
    at assignContextualParameterTypes (/projeto/node_modules/typescript/lib/typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (/projeto/node_modules/typescript/lib/typescript.js:41948:29)
    at checkExpressionWorker (/projeto/node_modules/typescript/lib/typescript.js:42959:28)
    at checkExpression (/projeto/node_modules/typescript/lib/typescript.js:42898:42)
    at checkExpressionCached (/projeto/node_modules/typescript/lib/typescript.js:42779:38)
    at checkReturnStatement (/projeto/node_modules/typescript/lib/typescript.js:45418:54)
    at checkSourceElement (/projeto/node_modules/typescript/lib/typescript.js:46763:28)
    at Object.forEach (/projeto/node_modules/typescript/lib/typescript.js:1506:30)
    at checkBlock (/projeto/node_modules/typescript/lib/typescript.js:44563:16)
    at checkSourceElement (/projeto/node_modules/typescript/lib/typescript.js:46742:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (/projeto/node_modules/typescript/lib/typescript.js:41990:21)
    at checkDeferredNodes (/projeto/node_modules/typescript/lib/typescript.js:46828:25)
    at checkSourceFileWorker (/projeto/node_modules/typescript/lib/typescript.js:46863:17)
    at checkSourceFile (/projeto/node_modules/typescript/lib/typescript.js:46842:13)
    at Object.forEach (/projeto/node_modules/typescript/lib/typescript.js:1506:30)
 @ ./node_modules/rxjs/observable/bindNodeCallback.js 2:36-76
 @ ./node_modules/rxjs/add/observable/bindNodeCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./node_modules/ngx-restangular/dist/esm/src/ngx-restangular-http.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./node_modules/rxjs/observable/BoundCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (/projeto/node_modules/typescript/lib/typescript.js:9341:17)
    at assignContextualParameterTypes (/projeto/node_modules/typescript/lib/typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (/projeto/node_modules/typescript/lib/typescript.js:41948:29)
    at checkExpressionWorker (/projeto/node_modules/typescript/lib/typescript.js:42959:28)
    at checkExpression (/projeto/node_modules/typescript/lib/typescript.js:42898:42)
    at checkExpressionCached (/projeto/node_modules/typescript/lib/typescript.js:42779:38)
    at checkReturnStatement (/projeto/node_modules/typescript/lib/typescript.js:45418:54)
    at checkSourceElement (/projeto/node_modules/typescript/lib/typescript.js:46763:28)
    at Object.forEach (/projeto/node_modules/typescript/lib/typescript.js:1506:30)
    at checkBlock (/projeto/node_modules/typescript/lib/typescript.js:44563:16)
    at checkSourceElement (/projeto/node_modules/typescript/lib/typescript.js:46742:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (/projeto/node_modules/typescript/lib/typescript.js:41990:21)
    at checkDeferredNodes (/projeto/node_modules/typescript/lib/typescript.js:46828:25)
    at checkSourceFileWorker (/projeto/node_modules/typescript/lib/typescript.js:46863:17)
    at checkSourceFile (/projeto/node_modules/typescript/lib/typescript.js:46842:13)
    at Object.forEach (/projeto/node_modules/typescript/lib/typescript.js:1506:30)
 @ ./node_modules/rxjs/observable/bindCallback.js 2:32-68
 @ ./node_modules/rxjs/add/observable/bindCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./node_modules/ngx-restangular/dist/esm/src/ngx-restangular-http.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts
`

See: https://github.com/angular/angular/issues/20095

**Comment by logvinoleg89** [comment]
Hi @bpalermo, please update to 1.1.2 version
