### ISSUE TITLE
metadata version mismatch for module error 

### ISSUE THREAD

**Issue by seusmanakram** [2muchcoffeecom/ngx-restangular#116]
installed using npm install ngx-restangular but running the angular app is giving this error

ERROR in Error: Metadata version mismatch for module 
E:/Angular/conFusion/node_modules/ngx-restangular/dist/esm/src/index.d.ts, found version 4, expected 3, resolving symbol AppModule in
E:/Angular/conFusion/src/app/app.module.ts, resolving symbol AppModule in E:/Angular/conFusion/src/app/app.
module.ts, resolving symbol AppModule in 
E:/Angular/conFusion/src/app/app.module.ts
    at Error (native)
    at syntaxError (E:\conFusion\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (E:\Angular\conFusion\node_modules\@angular\compiler\bundles\compiler.umd.js:25118:23)
    at StaticReflector.simplify (E:\Angular\conFusion\node_modules\@angular\compiler\bundles\compiler.umd.js:25130:13)
    at StaticReflector.annotations (E:\Angular\conFusion\node_modules\@angular\compiler\bundles\compiler.umd.js:24558:41)
    at _getNgModuleMetadata
 (E:\Angular\conFusion\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule 
(E:\Angular\conFusion\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule 
(E:\Angular\conFusion\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (E:\Angular\conFusion\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (E:\Angular\conFusion\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (E:\Angular\conFusion\node_modules\@ngtools\webpack\src\plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by logvinoleg89** [comment]
What version of the angular and ngx-restangular do you use?

**Comment by seusmanakram** [comment]
angular4 and npm install ng-restangular saves the version 1.1.* . Shall i specifically use the specified version for angular 4 as mentioned in the ngx-restangular documentation ?

**Comment by tairezzzz** [comment]
Yes, we had to change [documentation](https://github.com/2muchcoffeecom/ngx-restangular/blob/master/README.md#how-do-i-add-this-to-my-project-in-angular-4) a little. To install ngx-restangular for Angular 4 please run `npm install --save ngx-restangular@1.0.13`.
