### ISSUE TITLE
Error on Ionic build android --prod

### ISSUE THREAD

**Issue by naviens** [2muchcoffeecom/ngx-restangular#24]
Restangualr Breaks while `Ionic build android --prod`. 

**Info:**
Angular version :2.2.1
ng2-restangular version: 0.1.7
 
> npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "ionic:build" "--" "--prod"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build "--prod"`
npm ERR! Exit status 1

**Stack Trace:**
> [19:22:56]  build prod failed: Error encountered resolving symbol values statically. Function calls are not supported. 
            Consider replacing the function or lambda with a reference to an exported function (position 7:10 in the 
            original .ts file), resolving symbol RestangularFactory in 
            /home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.config.d.ts,
            resolving symbol RestangularModule in 
            /home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.module.d.ts,
            resolving symbol AppModule in /home/naveen/workspace/Navi/phonegap/ionicauth2/src/app/app.module.ts, 
            resolving symbol AppModule in /home/naveen/workspace/Navi/phonegap/ionicauth2/src/app/app.module.ts 
[19:22:56]  ionic-app-script task: "build" 
[19:22:56]  Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider 
            replacing the function or lambda with a reference to an exported function (position 7:10 in the original .ts 
            file), resolving symbol RestangularFactory in 
            /home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.config.d.ts,
            resolving symbol RestangularModule in 
            /home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.module.d.ts,
            resolving symbol AppModule in /home/naveen/workspace/Navi/phonegap/ionicauth2/src/app/app.module.ts, 
            resolving symbol AppModule in /home/naveen/workspace/Navi/phonegap/ionicauth2/src/app/app.module.ts 
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 7:10 in the original .ts file), resolving symbol RestangularFactory in /home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.config.d.ts, resolving symbol RestangularModule in /home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.module.d.ts, resolving symbol AppModule in /home/naveen/workspace/Navi/phonegap/ionicauth2/src/app/app.module.ts, resolving symbol AppModule in /home/naveen/workspace/Navi/phonegap/ionicauth2/src/app/app.module.ts
    at positionalError (/home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/@angular/compiler-cli/src/static_reflector.js:595:18)
    at simplifyInContext (/home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/@angular/compiler-cli/src/static_reflector.js:473:27)
    at StaticReflector.simplify (/home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/@angular/compiler-cli/src/static_reflector.js:478:22)
    at StaticReflector.annotations (/home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/@angular/compiler-cli/src/static_reflector.js:60:36)
    at NgModuleResolver.resolve (/home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/@angular/compiler/bundles/compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (/home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/@angular/compiler/bundles/compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /home/naveen/workspace/Navi/phonegap/ionicauth2/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)

**Comment by mackelito** [comment]
Im also getting this "Consider replacing the function or lambda with a reference to an exported function" error but on a clean cli based project (not using Ionic)

**Comment by mackelito** [comment]
https://github.com/2muchcoffeecom/ng2-restangular/issues/21
Solved this issue for me

**Comment by tairezzzz** [comment]
Thanks @mackelito
