### ISSUE TITLE
Unexpected value '[object Object]' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by yosefdishinger-zz** [2muchcoffeecom/ngx-restangular#9]
Getting only when attempting to import ng2-restangular, using the docs for "Quick Configuration"
The project is based on the https://github.com/AngularClass/angular2-webpack-starter repo.

> Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'(…)

Even removing the function from the .fromRoot(..) method, does nothing.  Setting a break point in the function shows it's not getting there at all. 

This is my **app.module.ts**

```typescript
  import { NgModule, ApplicationRef } from '@angular/core';
  import { CommonModule } from '@angular/common';
  import { BrowserModule } from '@angular/platform-browser';
  import { RouterModule } from '@angular/router';
  import { FormsModule } from '@angular/forms';
  import { HttpModule, XSRFStrategy, CookieXSRFStrategy } from '@angular/http';
  
  import { RestangularModule } from 'ng2-restangular';
  
  // ngrx/store components
  import { StoreModule } from '@ngrx/store';
  import { EffectsModule } from '@ngrx/effects';
  import { RouterStoreModule } from '@ngrx/router-store';
  import { StoreDevtoolsModule } from '@ngrx/store-devtools';
  
  import { MaterialModule } from '@angular/material';
  import { ComponentsModule } from './components/index';
  import { AuthenticationEffects } from './effects/authentication';
  import { UserEffects } from './effects/user';
  import { ListEffects } from './effects/lists';
  
  import { UserAuthenticatedGuard } from './guards/user-authenticated';
  import { PartnerLeadsService } from './services/partner-leads-service';
  import { AuthenticationService } from './services/authentication-service';
  import { ListsService } from './services/lists-service';
  
  // App is our top level component
  import { AppComponent } from './containers/app/app';
  import { LoginPageComponent } from './containers/login-page/login-page';
  import { LeadsPageComponent } from './containers/leads-page/leads-page';
  import { DashboardComponent } from './containers/dashboard/dashboard';
  
  import { routes } from './routes';
  import { reducer } from './reducers';
  
  @NgModule({
    imports: [ // import Angular's modules
      CommonModule,
      HttpModule,
      BrowserModule,
      FormsModule,
      MaterialModule.forRoot(),
      RestangularModule.forRoot((RestangularProvider) => {
        RestangularProvider.setBaseUrl('/api/v1/');
        RestangularProvider.setDefaultHeaders({
           'Authorization': 'Bearer UDXPx-Xko0w4BRKajozCVy20X11MRZs1'
        });
      }),
      ComponentsModule,
      RouterModule.forRoot(routes, { useHash: true }),
      StoreModule.provideStore(reducer),
      RouterStoreModule.connectRouter(),   
      StoreDevtoolsModule.instrumentOnlyWithExtension(),
    ],
    declarations: [
      AppComponent
    ],
    providers: [],
    bootstrap: [
      AppComponent
    ]
  })
  export class AppModule { }
```

**Comment by rshchpkn** [comment]
I couldn`t reproduce your issue, could you send more information about it?

**Comment by captainkovalsky** [comment]
@yosefdishinger How do you fix your issue? Could you provide an additional information about issues?

**Comment by mtraynham** [comment]
I'm getting this as well.  Albeit, I'm not using TypeScript, just ES6, so not sure if that has to do with anything...

Here's the error.

```
vendor.js:18861 Uncaught
SyntaxError {originalStack: "Error: Unexpected value '[object Object]' imported…23)↵    at http://0.0.0.0:3000/my-app.js:1:1", zoneAwareStack: "Error: Unexpected value '[object Object]' imported…23)↵    at http://0.0.0.0:3000/my-app.js:1:1", _nativeError: Error: Unexpected value '[object Object]' imported by the module 'IndexModule' at SyntaxError.Ba…}
message
    :
    (...)
name
    :
    (...)
originalStack
    :
    "Error: Unexpected value '[object Object]' imported by the module 'IndexModule'↵    at SyntaxError.ZoneAwareError (http://0.0.0.0:3000/vendor.js:77854:33)↵    at SyntaxError.BaseError [as constructor] (http://0.0.0.0:3000/vendor.js:82290:16)↵    at new SyntaxError (http://0.0.0.0:3000/vendor.js:6105:16)↵    at http://0.0.0.0:3000/vendor.js:18316:44↵    at Array.forEach (native)↵    at CompileMetadataResolver.getNgModuleMetadata (http://0.0.0.0:3000/vendor.js:18301:49)↵    at JitCompiler._loadModules (http://0.0.0.0:3000/vendor.js:55364:64)↵    at JitCompiler._compileModuleAndComponents (http://0.0.0.0:3000/vendor.js:55324:52)↵    at JitCompiler.compileModuleAsync (http://0.0.0.0:3000/vendor.js:55290:21)↵    at PlatformRef_._bootstrapModuleWithZone (http://0.0.0.0:3000/vendor.js:41447:25)↵    at PlatformRef_.bootstrapModule (http://0.0.0.0:3000/vendor.js:41422:21)↵    at Object.554 (http://0.0.0.0:3000/my-app.js:520:55)↵    at __webpack_require__ (http://0.0.0.0:3000/vendor.js:53:30)↵    at webpackJsonpCallback (http://0.0.0.0:3000/vendor.js:24:23)↵    at http://0.0.0.0:3000/my-app.js:1:1"
stack
    :
    (...)
zoneAwareStack
    :
    "Error: Unexpected value '[object Object]' imported by the module 'IndexModule'↵    at SyntaxError.ZoneAwareError (http://0.0.0.0:3000/vendor.js:77854:33)↵    at SyntaxError.BaseError [as constructor] (http://0.0.0.0:3000/vendor.js:82290:16)↵    at new SyntaxError (http://0.0.0.0:3000/vendor.js:6105:16)↵    at http://0.0.0.0:3000/vendor.js:18316:44↵    at Array.forEach (native)↵    at CompileMetadataResolver.getNgModuleMetadata (http://0.0.0.0:3000/vendor.js:18301:49)↵    at JitCompiler._loadModules (http://0.0.0.0:3000/vendor.js:55364:64)↵    at JitCompiler._compileModuleAndComponents (http://0.0.0.0:3000/vendor.js:55324:52)↵    at JitCompiler.compileModuleAsync (http://0.0.0.0:3000/vendor.js:55290:21)↵    at PlatformRef_._bootstrapModuleWithZone (http://0.0.0.0:3000/vendor.js:41447:25)↵    at PlatformRef_.bootstrapModule (http://0.0.0.0:3000/vendor.js:41422:21)↵    at Object.554 (http://0.0.0.0:3000/my-app.js:520:55)↵    at __webpack_require__ (http://0.0.0.0:3000/vendor.js:53:30)↵    at webpackJsonpCallback (http://0.0.0.0:3000/vendor.js:24:23)↵    at http://0.0.0.0:3000/my-app.js:1:1"
_nativeError
    :
    Error: Unexpected value '[object Object]' imported by the module 'IndexModule' at SyntaxError.BaseError [as constructor] (http://0.0.0.0:3000/vendor.js:82295:27) [<root>] at new SyntaxError (http://0.0.0.0:3000/vendor.js:6105:16) [<root>] at http://0.0.0.0:3000/vendor.js:18316:44 [<root>] at Array.forEach (native) [<root>] at CompileMetadataResolver.getNgModuleMetadata (http://0.0.0.0:3000/vendor.js:18301:49) [<root>] at JitCompiler._loadModules (http://0.0.0.0:3000/vendor.js:55364:64) [<root>] at JitCompiler._compileModuleAndComponents (http://0.0.0.0:3000/vendor.js:55324:52) [<root>] at JitCompiler.compileModuleAsync (http://0.0.0.0:3000/vendor.js:55290:21) [<root>] at PlatformRef_._bootstrapModuleWithZone (http://0.0.0.0:3000/vendor.js:41447:25) [<root>] at PlatformRef_.bootstrapModule (http://0.0.0.0:3000/vendor.js:41422:21) [<root>] at Object.554 (http://0.0.0.0:3000/my-app.js:520:55) [<root>] at __webpack_require__ (http://0.0.0.0:3000/vendor.js:53:30) [<root>] at webpackJsonpCallback (http://0.0.0.0:3000/vendor.js:24:23) [<root>] at http://0.0.0.0:3000/my-app.js:1:1 [<root>]
    __proto__
:
BaseError
CompileMetadataResolver._reportError	@	vendor.js:18861
(anonymous)	@	vendor.js:18316
CompileMetadataResolver.getNgModuleMetadata	@	vendor.js:18301
JitCompiler._loadModules	@	vendor.js:55364
JitCompiler._compileModuleAndComponents	@	vendor.js:55324
JitCompiler.compileModuleAsync	@	vendor.js:55290
PlatformRef_._bootstrapModuleWithZone	@	vendor.js:41447
PlatformRef_.bootstrapModule	@	vendor.js:41422
554	@	my-app.js:520
__webpack_require__	@	vendor.js:53
webpackJsonpCallback	@	vendor.js:24
(anonymous)	@	my-app.js:1
```

Seems like the `CompileMetadataResolver.getNgModuleMetadata` is returning null.

**Comment by Reggis** [comment]
I had a similar problem. It was caused by old version of angular/core. After updating everything with yarn works fine
