### ISSUE TITLE
not working with ionic 3.5 --prod flag

### ISSUE THREAD

**Issue by staskuban** [2muchcoffeecom/ngx-restangular#94]
Hi, i trying build project ionic 3.5  with --prod flag, and compiler throw that error
Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported.

**Comment by rshchpkn** [comment]
Hi @staskuban, I've tried restangular with latest ionic and it works ok. If you still can reproduce this bug please reopen issue with details.

**Comment by hectorNeira** [comment]
Can the Issue be reopened? I have the same Error. I'm using 
angular-cli: 1.0.0-beta.28.3 
node: 6.11.3
ionic: 3.15.2
ng2-restangular: "^0.1.30"

When I run ionic cordova run android --prod

`Running app-scripts build: --prod --platform android --target cordova
[13:07:20]  build prod started ... 
[13:07:20]  clean started ... 
[13:07:20]  clean finished in 1 ms 
[13:07:20]  copy started ... 
[13:07:20]  ngc started ... 
Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/hectorneira/Documents/white_label_app/simpplo-wl/node_modules/ng2-restangular/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Users/hectorneira/Documents/white_label_app/simpplo-wl/node_modules/ng2-restangular/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /Users/hectorneira/Documents/white_label_app/simpplo-wl/node_modules/ng2-restangular/node_modules/@angular/core/src/di/opaque_token.d.ts
    at Error (native)
    at syntaxError (/Users/hectorneira/Documents/white_label_app/simpplo-wl/node_modules/@angular/compiler/bundles/compiler.umd.js:1550:34)
    at simplifyInContext (/Users/hectorneira/Documents/white_label_app/simpplo-wl/node_modules/@angular/compiler/bundles/compiler.umd.js:23870:23)
    at StaticReflector.simplify (/Users/hectorneira/Documents/white_label_app/simpplo-wl/node_modules/@angular/compiler/bundles/compiler.umd.js:23882:13)
    at StaticReflector.annotations (/Users/hectorneira/Documents/white_label_app/simpplo-wl/node_modules/@angular/compiler/bundles/compiler.umd.js:23331:41)
    at NgModuleResolver.resolve (/Users/hectorneira/Documents/white_label_app/simpplo-wl/node_modules/@angular/compiler/bundles/compiler.umd.js:13883:70)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/hectorneira/Documents/white_label_app/simpplo-wl/node_modules/@angular/compiler/bundles/compiler.umd.js:14473:60)
    at addNgModule (/Users/hectorneira/Documents/white_label_app/simpplo-wl/node_modules/@angular/compiler/bundles/compiler.umd.js:23050:58)
    at /Users/hectorneira/Documents/white_label_app/simpplo-wl/node_modules/@angular/compiler/bundles/compiler.umd.js:23061:14
    at Array.forEach (native)`

Let me know if i need to provide more info.
